# Generated by Django 2.2.9 on 2020-02-14 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=50)),
                ('mgr_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('date_of_join', models.DateField()),
                ('emp_status', models.BooleanField(default=True)),
                ('mobile_no', models.CharField(blank=True, max_length=12)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Department')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fst_date', models.DateTimeField()),
                ('til_date', models.DateTimeField()),
                ('count', models.IntegerField()),
                ('reason', models.CharField(max_length=50)),
                ('leave_type', models.CharField(max_length=50)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_no', models.BigIntegerField()),
                ('basic_sal', models.IntegerField()),
                ('pf', models.IntegerField()),
                ('hra', models.IntegerField()),
                ('total_salary', models.IntegerField(blank=True, null=True)),
                ('date_of_month', models.DateTimeField()),
                ('count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Leave')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Position'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
