# Generated by Django 2.2.9 on 2020-02-14 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='leader',
        ),
    ]
